### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by dos1** [Blakkis/GLSL_Python#2]
The repository does not specify any license for the code, which means that nobody can legally use it without asking for permission. Given that these are pretty minimal examples which were most likely uploaded specifically to allow others to use them, learn from them and base their stuff on, I assume this wasn't the intention.

The best way to deal with it would be to create a `LICENSE` file with the text of selected license. Based on the implied purpose of the repository, some good options would likely be MIT or WTFPL. GitHub allows to easily create such file from the UI, see: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by Blakkis** [comment]
Done.

**Comment by Blakkis** [comment]
Yeah, intention was to provide "as minimal" as possible implementation for getting opengl up and running.

**Comment by dos1** [comment]
Thanks! :)
